language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
  # - "nightly"
  #- "pypy"
  # - "pypy3"
sudo: false
env:
  global:
    PYTHONIOENCODING=UTF-8
  matrix:
    # travis - strategy - lazy, server
    - USERDOMAIN=TRAVIS,SYNC,0,EDIR
    - USERDOMAIN=TRAVIS,SYNC,1,EDIR
    - USERDOMAIN=TRAVIS,ASYNC,0,EDIR
    - USERDOMAIN=TRAVIS,ASYNC,1,EDIR
    - USERDOMAIN=TRAVIS,RESTARTABLE,0,EDIR
    - USERDOMAIN=TRAVIS,RESTARTABLE,1,EDIR
    - USERDOMAIN=TRAVIS,REUSABLE,0,EDIR
    - USERDOMAIN=TRAVIS,REUSABLE,1,EDIR
    - USERDOMAIN=TRAVIS,SYNC,0,AD
    - USERDOMAIN=TRAVIS,SYNC,1,AD
    - USERDOMAIN=TRAVIS,ASYNC,0,AD
    - USERDOMAIN=TRAVIS,ASYNC,1,AD
    - USERDOMAIN=TRAVIS,RESTARTABLE,0,AD
    - USERDOMAIN=TRAVIS,RESTARTABLE,1,AD
    - USERDOMAIN=TRAVIS,REUSABLE,0,AD
    - USERDOMAIN=TRAVIS,REUSABLE,1,AD
install:
  - "pip install ."
  - "pip list"
script:
  - nosetests -s test
