language: python
python:
  #- "2.6"
  #- "2.7"
  - "3.4"
env:
  - USERDOMAIN=TRAVIS
  - STRATEGY=0
  - STRATEGY=1
  - LAZY=0
  - LAZY=1
install:
  - "pip install ."
script:
  - cd pureLDAP
  - python -m unittest discover
